server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    hosts:
      - argocd.example.com

configs:
  secret:
    argocdServerAdminPassword: "$2a$10$8E9kneY0PgsLDm/l8YLsDenDOSFm/o0vMIr3B8GZM4zDgll8X2Dji"  # Replace with your desired hashed password