apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: ghcr-auth
  namespace: argocd
spec:
  appName: ghcr-auth
  destination:
    create: true
    labels:
      hvs: "true"
    name: ghcr-auth
    namespace: argocd
  refreshAfter: 1h
