apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: argocd
spec:
  selector:
    app: service-hub-app
    # version: <This will be dynamically selected by Argo Rollouts>
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32173