apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-hub-app-blue
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-hub-app
      version: blue
  template:
    metadata:
      labels:
        app: service-hub-app
        version: blue
    spec:
      containers:
      - name: site
        image: ghcr.io/donanroherty/turborepo-github-actions/site
        ports:
        - containerPort: 3000
  strategy:
    blueGreen:
      activeService: service-hub-app-active
      previewService: service-hub-app-preview
      autoPromotionEnabled: true
