apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.0.0
          envFrom:
            - secretRef:
                name: argocd-secrets
