apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: argocd
resources:
  - manifests/apps/service-hub/production/rollout.yaml
images:
  - name: ghcr.io/donanroherty/turborepo-github-actions/site
    newTag: release-v1.0.2

