apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-hub-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-hub-app
  template:
    metadata:
      labels:
        app: service-hub-app
    spec:
      containers:
      - name: site
        image: ghcr.io/donanroherty/turborepo-github-actions/site
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-auth
        env:
        - name: GHCR_USERNAME
          valueFrom:
            secretKeyRef:
              name: ghcr-auth
              key: username
        - name: GHCR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ghcr-auth
              key: password
