apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/apps/service-hub/base/deployment.yaml
  - manifests/apps/service-hub/base/service.yaml

images:
  - name: ghcr.io/donanroherty/turborepo-github-actions/site
    newTag: latest

