apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-hub-app
  namespace: service-hub-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-hub-app
  template:
    metadata:
      labels:
        app: service-hub-app
    spec:
      containers:
      - name: site
        image: ghcr.io/donanroherty/turborepo-github-actions/site:staging
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-auth
