apiVersion: v1
kind: Service
metadata:
  name: service-hub-app-preview
  namespace: service-hub-ns
spec:
  selector:
    app: service-hub-app
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32175
  type: NodePort
