apiVersion: v1
kind: Service
metadata:
  name: service-hub-app-preview
  namespace: argocd
spec:
  selector:
    app: service-hub-app
    # version: <This will be dynamically selected by Argo Rollouts>
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32177
