apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-hub-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-hub-app
      version: production
  template:
    metadata:
      labels:
        app: service-hub-app
        version: production
    spec:
      containers:
      - name: site
        image: ghcr.io/donanroherty/turborepo-github-actions/site
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-auth
  strategy:
    blueGreen:
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
