version: '3.8'

services:
  github-runner:
    build: .
    network_mode: host
    environment:
      - REPO_URL=${REPO_URL}
      - REG_TOKEN=${REG_TOKEN}
      - PAT=${PAT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
