apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: service-hub-project
  namespace: argocd
spec:
  description: Project for Next.js application and related services
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  roles:
    - name: read-only
      description: Read-only access to the project
      policies:
        - p, proj:argocd:read-only, applications, get, argocd/*, allow
        - p, proj:n