name: Sealed Secrets

on:
  push:
    branches:
      - main

jobs:
  seal-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Connect to Kubernetes cluster
      run: |
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
        kubectl --kubeconfig=kubeconfig.yaml get nodes

    - name: Create Sealed Secret
      run: |
        kubectl --kubeconfig=kubeconfig.yaml create secret generic my-secret --dry-run=client --from-literal=foo=bar -o yaml | \
          kubeseal --controller-name=sealed-secrets --controller-namespace=sealed-secrets --format=yaml --cert=pub-sealed-secrets.pem > kubernetes/secrets/my-secret.yaml

    - name: Commit Sealed Secret
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add kubernetes/secrets/my-secret.yaml
        git commit -m "Add Sealed Secret"
        git push